[project]
authors = ["gnodar01 <gnodar01@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "MONAILabel"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
