[project]
authors = ["gnodar01 <gnodar01@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "MONAILabel"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.13"

[pypi-dependencies]
torch = ">=2.6.0, <3"
torchvision = ">=0.21.0, <0.22"
torchaudio = ">=2.6.0, <3"
