[project]
authors = ["gnodar01 <gnodar01@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "MONAILabel"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
monailabel = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib/python3.12/site-packages/monailabel/scripts/monailabel"
download_vista = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib/python3.12/site-packages/monailabel/scripts/monailabel apps --download --name vista2d --output apps"
serve_vista = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib/python3.12/site-packages/monailabel/scripts/monailabel start_server --app apps/vista2d --studies datasets --conf models vista2d --conf preload true --conf skip_trainers true"

[dependencies]
python = ">=3.10,<3.13"

[pypi-dependencies]
torch = ">=2.6.0, <3"
torchvision = ">=0.21.0, <0.22"
torchaudio = ">=2.6.0, <3"
monailabel = ">=0.8.5, <0.9"
cucim = ">=23.10.0, <24"
cupy-cuda12x = ">=13.3.0, <14"
cellpose = "==3.0.8"
natsort = "==8.4.0"
fastremap = "==1.15.0"
pydicom = "<3.0.0"
segment-anything = { git = "git+https://github.com/facebookresearch/segment-anything.git" }
